#!/usr/bin/with-contenv bash

# make our folders
mkdir -p /config/.config/DkVerwaltungQt

# set webserver port on first install
[[ ! -f /config/.config/DkVerwaltungQt/server-config.txt ]] && \
  echo "port 8081" > /config/.config/DkVerwaltungQt/server-config.txt

# permissions
chown -R abc:abc \
	/config \
	/opt/DkVerwaltungQt
